# .github/workflows/firebase_push.yml
name: FCM push on schedule

on:
  schedule:
    - cron: '*/5 * * * *'   # every 5 min
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
    # 1️⃣  Check out repo
    - uses: actions/checkout@v4

    # 2️⃣  Make service-account creds available as ADC
    - uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCLOUD_SA_KEY }}'
        project_id: ${{ secrets.GCP_PROJECT }}
        export_environment_variables: true

    # 3️⃣  Install gcloud CLI
    - uses: google-github-actions/setup-gcloud@v1

    # 4️⃣  Install jq (needed by the Bash script)
    - name: Install jq
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y jq

    # 5️⃣  Run the push script (ONE step, both env vars)
    - name: Run push script
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT }}
        RTDB_URL:  ${{ secrets.RTDB_URL }}
      run: |
        bash ./firebase_push.sh      # script is in repo root
