# .github/workflows/firebase_push.yml
name: FCM push on schedule

on:
  schedule:
    - cron: '*/5 * * * *'     # every 5 min
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
    - uses: actions/checkout@v4

    - uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCLOUD_SA_KEY }}'
        project_id: ${{ secrets.GCP_PROJECT }}
        export_environment_variables: true  # ensures ADC for gcloud

    - uses: google-github-actions/setup-gcloud@v1

    - name: Install jq
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y jq

    - name: Run push script
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT }}
      run: |
        bash ./firebase_push.sh
        
    - name: Run push script
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT }}
        RTDB_URL:  ${{ secrets.RTDB_URL }}     # ← new line
      run: |
        bash ./firebase_push.sh
