name: FCM push on schedule

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
    - uses: actions/checkout@v4

    # auth → Application-Default credentials
    - uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCLOUD_SA_KEY }}'
        project_id: ${{ secrets.GCP_PROJECT }}

    - uses: google-github-actions/setup-gcloud@v1

    # install jq (one-line, fast)
    - run: sudo apt-get update && sudo apt-get install -y jq

    - name: Run push script
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT }}
      run: |
        chmod +x ./firebase_push.sh
        ./firebase_push.sh
