name: Weather-Notify

on:
  schedule:
    - cron: '*/5 * * * *'     # every 5 minutes (UTC)
  workflow_dispatch:

permissions:
  contents: read

jobs:
  push-weather:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (code not strictly needed, but common practice)
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Run sendAlert.js
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          DATABASE_URL:             ${{ secrets.DATABASE_URL }}
          GOOGLE_CLOUD_PROJECT:     ${{ secrets.PROJECT_ID }}
        run: node scripts/sendAlert.js
